version: '1'
services:
  db:
    container_name: PostgresCont
    build: ./postgre
    restart: always
    volumes:
      - ./postgre/datapostgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=161200
    ports:
      - '5432:5432'
  server:
    container_name: server
    build: ./server
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/
      - /usr/src/node_modules
    ports:
      - '80:8000'
# volumes:
#   data:
#     driver: local
